// const usersList = [
//     { id: 1, name: 'Sasori', orderValue: '98765', status: 'Active', quantity: '7', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 2, name: 'Hinata Hyuga', orderValue: '123456', status: 'Active', quantity: '5', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 3, name: 'Itachi Uchiha', orderValue: '456789', status: 'Not Active', quantity: '9', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 4, name: 'Naruto Uzumaki', orderValue: '2378344', status: 'Active', quantity: '13', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 5, name: 'Kakashi Hatake', orderValue: '345678', status: 'Not Active', quantity: '12', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 6, name: 'Sasuke Uchiha', orderValue: '189234', status: 'Not Active', quantity: '8', img: 'https://w0.peakpx.com/wallpaper/878/815/HD-wallpaper-sasuke-uchiha-sasuke-uchiha-naruto-anime.jpg' },
//     { id: 7, name: 'Shikamaru Nara', orderValue: '234567', status: 'Not Active', quantity: '10', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 8, name: 'Gaara', orderValue: '67890', status: 'Active', quantity: '3', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 9, name: 'Jiraiya', orderValue: '45678', status: 'Not Active', quantity: '6', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 10, name: 'Monkey D. Luffy', orderValue: '3456789', status: 'Active', quantity: '11', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 11, name: 'tachi Uchiha', orderValue: '56789', status: 'Active', quantity: '4', img: 'https://w0.peakpx.com/wallpaper/160/785/HD-wallpaper-itachi-uchiha-akatsuki-anime-japan-naruto-naruto-shippuden-sasuke-sharingan-uchiha-itachi.jpg' },
//     { id: 12, name: 'Roronoa Zoro', orderValue: '237834', status: 'Active', quantity: '9', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 13, name: 'Nami', orderValue: '123456', status: 'Not Active', quantity: '7', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 14, name: 'Sanji', orderValue: '98765', status: 'Active', quantity: '8', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//     { id: 15, name: 'Tony Tony Chopper', orderValue: '234567', status: 'Not Active', quantity: '4', img: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg' },
//   ];

  export const userOrderData = [
    {
      id: 1,
      product_name: 'Hp Pavilion 15',
      price: '659499',
      customer: 'Naruto Uzumaki',
      status: 'Completed',
      profileImage: 'https://img.etimg.com/thumb/msid-102703009,width-300,height-225,imgsize-16886,,resizemode-75/starting-naruto-check-where-to-begin-how-to-watch-heres-your-complete-guide-to-iconic-ninja-series.jpg',
      quantity: 10,
    },
    {
      id: 2,
      product_name: 'Dell XPS 13',
      price: '794999',
      customer: 'Monkey D Luffy',
      status: 'Pending',
      profileImage: 'https://w0.peakpx.com/wallpaper/937/956/HD-wallpaper-luffy-anime-anime-luffy-luufy-monkey-d-luffy-monkey-d-luffy-one-piece-smile.jpg',
      quantity: 15,
    },
    {
      id: 3,
      product_name: 'MacBook Pro',
      price: '1299499',
      customer: 'Tobirama Senju',
      status: 'Completed',
      profileImage: 'https://w0.peakpx.com/wallpaper/1005/847/HD-wallpaper-tobirama-senju-naruto-uchiha-ninja-shippuden-leaf-hashirama.jpg',
      quantity: 8,
    },
    {
      id: 4,
      product_name: 'Lenovo ThinkPad',
      price: '549499',
      customer: 'Kakashi Hatake',
      status: 'Declined',
      profileImage: 'https://w0.peakpx.com/wallpaper/458/866/HD-wallpaper-kakashi-kakashi-sensei.jpg',
      quantity: 20,
    },
    {
      id: 5,
      product_name: 'Asus ROG Zephyrus',
      price: '899599',
      customer: 'Zoro Bushido',
      status: 'Pending',
      profileImage: 'https://w0.peakpx.com/wallpaper/225/916/HD-wallpaper-zoro-one-piece.jpg',
      quantity: 12,
    },
    {
      id: 6,
      product_name: 'Acer Predator Helios',
      price: '749099',
      customer: 'Hinata Hyuga',
      status: 'Completed',
      profileImage: 'https://w0.peakpx.com/wallpaper/457/652/HD-wallpaper-hinata-naruto.jpg',
      quantity: 18,
    },
    {
      id: 7,
      product_name: 'Microsoft Surface Laptop',
      price: '894599',
      customer: 'Itachi Uchiha',
      status: 'Declined',
      profileImage: 'https://w0.peakpx.com/wallpaper/160/785/HD-wallpaper-itachi-uchiha-akatsuki-anime-japan-naruto-naruto-shippuden-sasuke-sharingan-uchiha-itachi.jpg',
      quantity: 7,
    },
    {
      id: 8,
      product_name: 'HP Envy 13',
      price: '699909',
      customer: 'Sasuke Uchiha',
      status: 'Completed',
      profileImage: 'https://w0.peakpx.com/wallpaper/878/815/HD-wallpaper-sasuke-uchiha-sasuke-uchiha-naruto-anime.jpg',
      quantity: 14,
    },
    // Add 10 more objects below
    {
      id: 9,
      product_name: 'Acer Aspire 5',
      price: '48999',
      customer: 'Sakura Haruno',
      status: 'Pending',
      profileImage: 'https://example.com/sakura.jpg',
      quantity: 17,
    },
    {
      id: 10,
      product_name: 'Samsung Galaxy S21',
      price: '79999',
      customer: 'Goku',
      status: 'Completed',
      profileImage: 'https://example.com/goku.jpg',
      quantity: 11,
    },
    {
      id: 11,
      product_name: 'Sony PlayStation 5',
      price: '49999',
      customer: 'Vegeta',
      status: 'Pending',
      profileImage: 'https://example.com/vegeta.jpg',
      quantity: 23,
    },
    {
      id: 12,
      product_name: 'Google Pixel 6',
      price: '89999',
      customer: 'Ichigo Kurosaki',
      status: 'Completed',
      profileImage: 'https://example.com/ichigo.jpg',
      quantity: 14,
    },
    {
      id: 13,
      product_name: 'Xbox Series X',
      price: '54999',
      customer: 'Sakamoto',
      status: 'Declined',
      profileImage: 'https://example.com/sakamoto.jpg',
      quantity: 8,
    },
    {
      id: 14,
      product_name: 'LG OLED TV',
      price: '129999',
      customer: 'Lelouch Lamperouge',
      status: 'Completed',
      profileImage: 'https://example.com/lelouch.jpg',
      quantity: 19,
    },
    {
      id: 15,
      product_name: 'Nintendo Switch',
      price: '29999',
      customer: 'Light Yagami',
      status: 'Pending',
      profileImage: 'https://example.com/light.jpg',
      quantity: 6,
    },
    {
      id: 16,
      product_name: 'DJI Mavic Air 2',
      price: '79999',
      customer: 'Eren Yeager',
      status: 'Completed',
      profileImage: 'https://example.com/eren.jpg',
      quantity: 15,
    },
    {
      id: 17,
      product_name: 'Bose QuietComfort 35 II',
      price: '24999',
      customer: 'Mikasa Ackerman',
      status: 'Declined',
      profileImage: 'https://example.com/mikasa.jpg',
      quantity: 10,
    }
]